language: node_js
node_js:
  - 8.9.4
  - 9
script:
  - npm run cover
  - npm run lint
  - npm run docs
after_script:
  - codecov
  - cat ./build/coverage/lcov.info | coveralls
  - npm run docs
sudo: false
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
notifications:
  email:
    - markus.felten@gmx.de
before_install:
  - npm i -g npm@latest
before_script:
  - npm prune
  - npm install -g --production coveralls codecov
after_success:
  - npm run semantic-release
