language: node_js
os:
  - linux
  - osx
node_js:
  - 10.14
script:
  - npm run cover
  - npm run lint
  - npm run docs
after_script:
  - codecov
  - cat ./coverage/lcov.info | coveralls
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache: npm
notifications:
  email:
    - markus.felten@gmx.de
before_script:
  - npm prune
  - npm install -g --production coveralls codecov
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
